Tensors Basics

In [ ]:
# Tensors are multi-dimensional arrays - like NumPy arrays
# Difference: accelerated memory (GPU/TPU), non-numerical data types, non-rectangular
# Tensorflow tensors are immutable (cannot be changed), PyTorch tensors are mutable
# Tensors can broadcast information (mathematical arrays cannot)
# Tensors include programmatic attributes and methods (not part of mathematics)

In [1]:
# helpers.py file contains functions to print and do some operations on tensors
import sys
import torch
import helpers as h

In [2]:
# Printing the python and pytorch version (using the functions in helpers.py)
h.print_python_version()
h.print_pytorch_version()

Python version: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
pyTorch version: 2.1.2+cpu


In [3]:
# Initializing 1D-tensor with 2 floating-point numbers 1.0 & 2.0
x = torch.tensor([1., 2.])
h.print_tensor_info(x)

tensor([1., 2.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (2,)


In [6]:
x.device.type

'cpu'

In [10]:
# 1D tensor with single value
# ',' does not change anything

x = torch.tensor([1.,])
h.print_tensor_info(x)

tensor([1.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (1,)


In [ ]:
# Rank: Dimensionality - Number of axes in a tensor. (1D/2D/3D/...)
# Shape: Tuple containing number of elements in each axis.

In [11]:
# Rank-0 tensor without any list
x = torch.tensor(2.5)
h.print_tensor_info(x)

2.5
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    0
Shape        ()


In [12]:
# Rank-2 tensor
x = torch.tensor([[1., 2.],[3., 4.]])
h.print_tensor_info(x)

tensor([[1., 2.],
        [3., 4.]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    2
Shape        (2, 2)


In [13]:
# Rank-3 Tensor
x = torch.tensor([
    [[1.,],[2.,]],
    [[3.,],[4.,]],
    [[5.,],[6.,]],
    ])
h.print_tensor_info(x)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    3
Shape        (3, 2, 1)


In [14]:
# Defining data type of tensor explicitly
x = torch.tensor([1.], dtype=torch.double)
h.print_tensor_info(x)

tensor([1.], dtype=torch.float64)
Type         <class 'torch.Tensor'>
dtype        torch.float64
Dimension    1
Shape        (1,)


In [17]:
# We can define the tensor using torch.tensor constructor or torch.Tensor
x = torch.Tensor([1.])
h.print_tensor_info(x)

tensor([1.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (1,)


In [19]:
# torch.Tensor is an alias for torch.FloatTensor
# So, if we use torch.Tensor, it's data type is float by defaultprint(type(torch.tensor))
print(type(torch.tensor))
print(type(torch.Tensor))

<class 'builtin_function_or_method'>
<class 'torch._C._TensorMeta'>


In [16]:
# Tensor with integer value
x = torch.IntTensor([1])
h.print_tensor_info(x)

tensor([1], dtype=torch.int32)
Type         <class 'torch.Tensor'>
dtype        torch.int32
Dimension    1
Shape        (1,)


In [20]:
# Rank-2 Tensor
x = torch.tensor([
    [1., 2.],
    [3., 4.],
    [5., 6.],
    ])
h.print_tensor_info(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    2
Shape        (3, 2)


In [21]:
# Accessing element - row 2 and column 1
x[1,0]

tensor(3.)

In [22]:
# Rank-3 Tensor
x = torch.tensor([
    [[1., 2.],[3., 4.]],
    [[5., 6.],[7., 8.]],
    [[9., 10.],[11., 12.]],
    ])
h.print_tensor_info(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    3
Shape        (3, 2, 2)


In [23]:
# Accessing all elements of row 1
x[0]

tensor([[1., 2.],
        [3., 4.]])

In [24]:
# Accessing element
x[0][0][0]

tensor(1.)

In [25]:
# Slicing syntax: [start:stop:stop]
# First 0 refers to first element of 3x2x2 which is the first 2x2 matrix
# : refers to all elements so whole matrix
# Second 0 refers to Which row of each element to select which is first element of each row
x[0,:,0]

tensor([1., 3.])

In [28]:
# 0:2 = First 2 matrices (2 is expluded here)
# 0 = First row of all 3 matrix
# 0 = First element of all rows
x[0:2,0,0]

tensor([1., 5.])

In [29]:
# Assign values (Only in PyTorch, not in Tensorflow)
x[1,1,1] = 100

In [30]:
x

tensor([[[  1.,   2.],
         [  3.,   4.]],

        [[  5.,   6.],
         [  7., 100.]],

        [[  9.,  10.],
         [ 11.,  12.]]])

Tensor Operations

In [31]:
# Using '_' with the operation does in-place change.
# So, x will be modified after the operation.
# Saves memory

tensor = torch.ones(2, 2)
print(tensor, "\n")
tensor.add_(5)  # notice the underscore
print(tensor)

tensor([[1., 1.],
        [1., 1.]]) 

tensor([[6., 6.],
        [6., 6.]])


In [33]:
tensor = torch.ones(2, 2)
print(tensor, "\n")
tensor.add(5)  # no underscore
print(tensor, "\n")
new_tensor = tensor.add(5)
print(new_tensor)

tensor([[1., 1.],
        [1., 1.]]) 

tensor([[1., 1.],
        [1., 1.]]) 

tensor([[6., 6.],
        [6., 6.]])


In [34]:
# Define 2 tensors
x = torch.tensor([1., 2.])
y = torch.tensor([3., 4.])
print(f'x: {x}')
print(f'y: {y}')

x: tensor([1., 2.])
y: tensor([3., 4.])


In [35]:
# Arithmetic operations
print(f'x + y : {x + y}')
print(f'x - y : {x - y}')
print(f'x * y : {x * y}')
print(f'x / y : {x / y}')

x + y : tensor([4., 6.])
x - y : tensor([-2., -2.])
x * y : tensor([3., 8.])
x / y : tensor([0.3333, 0.5000])


In [37]:
# Dot product
print(f'x . y : {x.dot(y)}')
print(f'y . x : {y.dot(x)}')

x . y : 11.0
y . x : 11.0


In [41]:
# Matrix multiplication
x = torch.tensor([[1., 2.],[3., 4.]])
y = torch.tensor([[5., 6.],[7., 8.]])
print(x)
print(y)
print("\nMatrix Multiplications: \n")
print(torch.matmul(x, y))

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])

Matrix Multiplications: 

tensor([[19., 22.],
        [43., 50.]])


In [43]:
# Other matrix multiplication methods
# x.matmul(y)
# x@y
# If 2 tensors with 1D gets multiplied using matmul, it returns answer for dot product.

tensor([[19., 22.],
        [43., 50.]])

In [44]:
# If 2 different size matrix uses matmul, PyTorch will add the extra row with 0 values
x = torch.tensor([1., 2.])
y = torch.tensor([[3., 4.],[5., 6.]])
print(x)
print(y)
print(torch.matmul(x,y))

tensor([1., 2.])
tensor([[3., 4.],
        [5., 6.]])
tensor([13., 16.])


In [47]:
# If first tensor is 2D and second tensor is 1D, output is matrix-vector product.
x = torch.tensor([1., 2.])
y = torch.tensor([[3., 4.],[5., 6.]])
print(x)
print(y)

print("\nMatrix Multiplications:")
torch.matmul(y,x)

tensor([1., 2.])
tensor([[3., 4.],
        [5., 6.]])

Matrix Multiplications:


tensor([11., 17.])

In [ ]:
# matmul is used only when any one tensor is of rank-2